/******************************************************************************/
/***         Generated by @felipealbuquerq 15/07/2018 11:27:01          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

CREATE DATABASE '127.0.0.1:C:\EfCoreTest.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;

/******************************************************************************/
/***         EXEC WITH FIREBIRD ISQL TOOL - COMMIT TRANSACTION = Y          ***/
/******************************************************************************/